server:
  port: 10021

spring:
  application:
    name: fegin-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"