server:
  port: 10031
spring:
  application:
    name: service-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  #    strip-prefix来决定是否需要前缀，true是不加前缀（默认），false就会添加到路径上
  #    zuul默认给我们如下的跳转规则：http://IP:port/ribbon/***  ====》http://IP:port/***
  #    false 时: http://IP:port/ribbon/***  ====》http://IP:port/ribbon/***
  routes:
    api-ribbon:
      path: /ribbon/**
      stripPrefix: false
      serviceId: ribbon-consumer
    api-feign:
      path: /feign/**
      stripPrefix: false
      serviceId: feign-consumer
ribbon:
  eureka:
    enabled: false
  ReadTimeout: 60000
  ConnectTimeout: 60000
ribbon-consumer:
  ribbon:
    listOfServers: 127.0.0.1:10011
feign-consumer:
  ribbon:
    listOfServers: 127.0.0.1:10021

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
