server:
  port: 10000

eureka:
  instance:
    hostname: localhost
  client:
    #表示是否将自己注册在EurekaServer上，默认为true。由于当前应用就是EurekaServer，所以置为false
    register-with-eureka: false
    #表示表示是否从EurekaServer获取注册信息，默认为true。单节点不需要同步其他的EurekaServer节点的数据,所以设置为false
    fetch-registry: false
    #设置Eureka的地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
